/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.daw1.juan.wordle.gui;

import java.util.regex.Pattern;
import org.daw1.juan.wordle.motores.*;

/**
 *
 * @author juan navarrete
 */
public class GestorMotorGUI extends javax.swing.JDialog {

    private IMotor motor; 
    /**
     * Creates new form GestorMotorGUI
     */
    public GestorMotorGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        motor = new MotorFichero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainControlesJPanel = new javax.swing.JPanel();
        TitulojPanel = new javax.swing.JPanel();
        GestionTitulojLabel = new javax.swing.JLabel();
        InferiorjPanel = new javax.swing.JPanel();
        AltaPalabrajPanel = new javax.swing.JPanel();
        anadirPalabrajPanel = new javax.swing.JPanel();
        AddPalabraTextField = new javax.swing.JTextField();
        AnadirjButton = new javax.swing.JButton();
        errorAnadirjPanel = new javax.swing.JPanel();
        addErrorjLabel = new javax.swing.JLabel();
        borrarjPanel = new javax.swing.JPanel();
        borrarPalabrajPanel = new javax.swing.JPanel();
        BorrarjTextField = new javax.swing.JTextField();
        BorrarjButton1 = new javax.swing.JButton();
        errorBorrarjPanel = new javax.swing.JPanel();
        removeErrorjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainControlesJPanel.setLayout(new java.awt.BorderLayout());

        TitulojPanel.setBackground(new java.awt.Color(204, 204, 204));
        TitulojPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TitulojPanel.setPreferredSize(new java.awt.Dimension(509, 80));
        TitulojPanel.setLayout(new java.awt.GridBagLayout());

        GestionTitulojLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        GestionTitulojLabel.setForeground(new java.awt.Color(0, 0, 0));
        GestionTitulojLabel.setText("Gestion Motor");
        TitulojPanel.add(GestionTitulojLabel, new java.awt.GridBagConstraints());

        mainControlesJPanel.add(TitulojPanel, java.awt.BorderLayout.NORTH);

        InferiorjPanel.setBackground(new java.awt.Color(153, 153, 153));
        InferiorjPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InferiorjPanel.setLayout(new java.awt.GridLayout(2, 1));

        AltaPalabrajPanel.setBackground(new java.awt.Color(204, 204, 204));
        AltaPalabrajPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta Palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        AltaPalabrajPanel.setLayout(new java.awt.GridLayout(2, 1));

        anadirPalabrajPanel.setBackground(new java.awt.Color(204, 204, 204));

        AddPalabraTextField.setPreferredSize(new java.awt.Dimension(120, 24));
        anadirPalabrajPanel.add(AddPalabraTextField);

        AnadirjButton.setBackground(new java.awt.Color(204, 204, 204));
        AnadirjButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AnadirjButton.setForeground(new java.awt.Color(0, 0, 0));
        AnadirjButton.setText("Añadir");
        AnadirjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnadirjButton.setPreferredSize(new java.awt.Dimension(75, 25));
        AnadirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirjButtonActionPerformed(evt);
            }
        });
        anadirPalabrajPanel.add(AnadirjButton);

        AltaPalabrajPanel.add(anadirPalabrajPanel);

        errorAnadirjPanel.setBackground(new java.awt.Color(204, 204, 204));
        errorAnadirjPanel.setLayout(new java.awt.GridBagLayout());

        addErrorjLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addErrorjLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorAnadirjPanel.add(addErrorjLabel, new java.awt.GridBagConstraints());

        AltaPalabrajPanel.add(errorAnadirjPanel);

        InferiorjPanel.add(AltaPalabrajPanel);

        borrarjPanel.setBackground(new java.awt.Color(204, 204, 204));
        borrarjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrado Palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        borrarjPanel.setForeground(new java.awt.Color(0, 0, 0));
        borrarjPanel.setLayout(new java.awt.GridLayout(2, 1));

        borrarPalabrajPanel.setBackground(new java.awt.Color(204, 204, 204));

        BorrarjTextField.setPreferredSize(new java.awt.Dimension(120, 24));
        BorrarjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarjTextFieldActionPerformed(evt);
            }
        });
        borrarPalabrajPanel.add(BorrarjTextField);

        BorrarjButton1.setBackground(new java.awt.Color(204, 204, 204));
        BorrarjButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BorrarjButton1.setForeground(new java.awt.Color(0, 0, 0));
        BorrarjButton1.setText("Borrar");
        BorrarjButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BorrarjButton1.setMinimumSize(new java.awt.Dimension(75, 25));
        BorrarjButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        BorrarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarjButton1ActionPerformed(evt);
            }
        });
        borrarPalabrajPanel.add(BorrarjButton1);

        borrarjPanel.add(borrarPalabrajPanel);

        errorBorrarjPanel.setBackground(new java.awt.Color(204, 204, 204));
        errorBorrarjPanel.setLayout(new java.awt.GridBagLayout());

        removeErrorjLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        removeErrorjLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorBorrarjPanel.add(removeErrorjLabel, new java.awt.GridBagConstraints());

        borrarjPanel.add(errorBorrarjPanel);

        InferiorjPanel.add(borrarjPanel);

        mainControlesJPanel.add(InferiorjPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainControlesJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainControlesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnadirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirjButtonActionPerformed
        if(!Pattern.compile("[a-zA-Z]{5}").matcher(this.AddPalabraTextField.getText()).matches()){
          addErrorjLabel.setForeground(new java.awt.Color(255,0,0));
          addErrorjLabel.setText("La palabra no es valida.");
          this.AddPalabraTextField.setText(null);
      }else if(motor.existePalabra(this.AddPalabraTextField.getText().toUpperCase())){
            addErrorjLabel.setForeground(new java.awt.Color(255,0,0));
          addErrorjLabel.setText("La palabra ya existe.");
          this.AddPalabraTextField.setText(null);
      }else{
         motor.addPalabra(this.AddPalabraTextField.getText()); 
         this.AddPalabraTextField.setText(null);
         addErrorjLabel.setForeground(new java.awt.Color(0,153,0));
         addErrorjLabel.setText("Palabra añadida con exito.");
    }//GEN-LAST:event_AnadirjButtonActionPerformed
    }
    private void BorrarjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarjTextFieldActionPerformed

    private void BorrarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarjButton1ActionPerformed
              if(!motor.removePalabra(this.BorrarjTextField.getText())){
            this.removeErrorjLabel.setForeground(new java.awt.Color(255,0,0));
            this.removeErrorjLabel.setText("La palabra insertada no existe.");
            this.BorrarjTextField.setText(null);
            
        }else{
            this.removeErrorjLabel.setForeground(new java.awt.Color(0,153,0));
            this.removeErrorjLabel.setText("Palabra borrada con exito.");  
            this.BorrarjTextField.setText(null);
        }
    }//GEN-LAST:event_BorrarjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorMotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorMotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorMotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorMotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestorMotorGUI dialog = new GestorMotorGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddPalabraTextField;
    private javax.swing.JPanel AltaPalabrajPanel;
    private javax.swing.JButton AnadirjButton;
    private javax.swing.JButton BorrarjButton1;
    private javax.swing.JTextField BorrarjTextField;
    private javax.swing.JLabel GestionTitulojLabel;
    private javax.swing.JPanel InferiorjPanel;
    private javax.swing.JPanel TitulojPanel;
    private javax.swing.JLabel addErrorjLabel;
    private javax.swing.JPanel anadirPalabrajPanel;
    private javax.swing.JPanel borrarPalabrajPanel;
    private javax.swing.JPanel borrarjPanel;
    private javax.swing.JPanel errorAnadirjPanel;
    private javax.swing.JPanel errorBorrarjPanel;
    private javax.swing.JPanel mainControlesJPanel;
    private javax.swing.JLabel removeErrorjLabel;
    // End of variables declaration//GEN-END:variables
}
